CREATE TABLE QR_API_LOG (
   TOKEN varchar(20) NOT NULL,
   API_REQUEST varchar(8000) NOT NULL,
   API_RESPONSE varchar(8000) NOT NULL,
   LOG_TIME datetime NOT NULL
 ) ENGINE=InnoDB DEFAULT CHARSET=latin1