CREATE TABLE PACKETFILE (
   ID int(11) NOT NULL AUTO_INCREMENT,
   PKT_NAME varchar(80) NOT NULL DEFAULT ' ',
   NO_OF_TIME_VERIFIED int(11) NOT NULL DEFAULT '0',
   FILE_NAME text,
   FILE_SIZE int(10) DEFAULT NULL,
   FILE_CHECKSUM text,
   FILE_UPLOADED_ON datetime DEFAULT NULL,
   FILE_EXECUTION_TIME double DEFAULT NULL,
   PRIMARY KEY (ID)
 ) ENGINE=InnoDB AUTO_INCREMENT=2775 DEFAULT CHARSET=latin1